INSERT INTO avatars (name) VALUES ('aubergine.png');
INSERT INTO avatars (name) VALUES ('beer.png');
INSERT INTO avatars (name) VALUES ('birthday-cake.png');
INSERT INTO avatars (name) VALUES ('biscuit.png');
INSERT INTO avatars (name) VALUES ('bread.png');
INSERT INTO avatars (name) VALUES ('breakfast.png');
INSERT INTO avatars (name) VALUES ('brochettes.png');
INSERT INTO avatars (name) VALUES ('burger.png');
INSERT INTO avatars (name) VALUES ('carrot.png');
INSERT INTO avatars (name) VALUES ('cheese.png');
INSERT INTO avatars (name) VALUES ('chicken-1.png');
INSERT INTO avatars (name) VALUES ('chicken.png');
INSERT INTO avatars (name) VALUES ('chocolate-1.png');
INSERT INTO avatars (name) VALUES ('chocolate-2.png');
INSERT INTO avatars (name) VALUES ('chocolate.png');
INSERT INTO avatars (name) VALUES ('cocktail.png');
INSERT INTO avatars (name) VALUES ('coffee.png');
INSERT INTO avatars (name) VALUES ('coke.png');
INSERT INTO avatars (name) VALUES ('covering.png');
INSERT INTO avatars (name) VALUES ('croissant.png');
INSERT INTO avatars (name) VALUES ('cup.png');
INSERT INTO avatars (name) VALUES ('cupcake.png');
INSERT INTO avatars (name) VALUES ('donut.png');
INSERT INTO avatars (name) VALUES ('egg.png');
INSERT INTO avatars (name) VALUES ('fish.png');
INSERT INTO avatars (name) VALUES ('fries.png');
INSERT INTO avatars (name) VALUES ('honey.png');
INSERT INTO avatars (name) VALUES ('hot-dog.png');
INSERT INTO avatars (name) VALUES ('icecream.png');
INSERT INTO avatars (name) VALUES ('jam.png');
INSERT INTO avatars (name) VALUES ('jelly.png');
INSERT INTO avatars (name) VALUES ('juice.png');
INSERT INTO avatars (name) VALUES ('ketchup.png');
INSERT INTO avatars (name) VALUES ('lemon.png');
INSERT INTO avatars (name) VALUES ('lettuce.png');
INSERT INTO avatars (name) VALUES ('loaf.png');
INSERT INTO avatars (name) VALUES ('milk.png');
INSERT INTO avatars (name) VALUES ('noodles.png');
INSERT INTO avatars (name) VALUES ('pepper.png');
INSERT INTO avatars (name) VALUES ('pickles.png');
INSERT INTO avatars (name) VALUES ('pie.png');
INSERT INTO avatars (name) VALUES ('pizza.png');
INSERT INTO avatars (name) VALUES ('rice.png');
INSERT INTO avatars (name) VALUES ('sausage.png');
INSERT INTO avatars (name) VALUES ('spaguetti.png');
INSERT INTO avatars (name) VALUES ('steak.png');
INSERT INTO avatars (name) VALUES ('tea.png');
INSERT INTO avatars (name) VALUES ('water-glass.png');
INSERT INTO avatars (name) VALUES ('watermelon.png');
INSERT INTO avatars (name) VALUES ('wine.png');

INSERT INTO measurement_types (name) VALUES ('Weight');
INSERT INTO measurement_types (name) VALUES ('Volume');
INSERT INTO measurement_types (name) VALUES ('Unit');

INSERT INTO measurement_units (name, abbreviation, measurement_type_id, convertion, created_at, updated_at) VALUES ('Gram', 'g', 1, 1, NOW(), NOW());
INSERT INTO measurement_units (name, abbreviation, measurement_type_id, convertion, created_at, updated_at) VALUES ('Kilogram', 'kg', 1, 1000, NOW(), NOW());
INSERT INTO measurement_units (name, abbreviation, measurement_type_id, convertion, created_at, updated_at) VALUES ('Mililiter', 'mL', 2, 1, NOW(), NOW());
INSERT INTO measurement_units (name, abbreviation, measurement_type_id, convertion, created_at, updated_at) VALUES ('Liter', 'L', 2, 1000, NOW(), NOW());
INSERT INTO measurement_units (name, abbreviation, measurement_type_id, convertion, created_at, updated_at) VALUES ('Unit', '', 3, NULL, NOW(), NOW());